# -*- coding: utf-8 -*-
"""T4SG Deliverable: Data Component.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1938md5uCAGHOv-5oZjR-Q3CxewdPnTml
"""

!pip install word2number
from word2number import w2n
import pandas as pd
import numpy as np
import re

df = pd.read_csv("Messy Animal Data - Animal Dataset (1).csv")
df.head()

def has_numeric_part(input):

    # has_numeric_part is defined as "whether or not the first or last character is a digit"
    # if neither the first nor last character is a digit, then nothing adjacent to the hyphen (if there is a hyphen) is a digit
    # then, we can conclude that there is no numeric part of the string

    has_numeric_part = False

    try:
        float(input[0])
        has_numeric_part = True
    except (ValueError, TypeError):
        pass

    try:
        float(input[-1])
        has_numeric_part = True
    except (ValueError, TypeError):
        pass

    return has_numeric_part

def get_numeric_part(input):
    numeric_part = ""
    for char in input:
        if char == ".":
            numeric_part += char
        else:
            try:
                numeric_part += str(int(char))
            except (ValueError, TypeError):
                break

    if numeric_part != "":
        return float(numeric_part)

    for char in input[::-1]:
        try:
            numeric_part = str(float(char)) + numeric_part
        except (ValueError, TypeError):
            break

    return float(numeric_part)


def clean_speed_column(speed):
    speed_range = [x.strip() for x in speed.split("-")]
    assert(len(speed_range) <= 2 and len(speed_range) > 0)

    if (all([has_numeric_part(speed) for speed in speed_range])):
        return sum([get_numeric_part(speed) for speed in speed_range]) / len(speed_range)
    else:
        try:
            return w2n.word_to_num(speed)
        except (ValueError, TypeError):
            print(f"Something went wrong with the following query: {speed}")
            return pd.NA

df["Average Speed (km/h)"] = df["Average Speed (km/h)"].apply(clean_speed_column)

def clean_diet_column(diet):
    diet_keywords = {
        "Omnivore": ["Omnivore", "Scavenger"],        # Most scavengers are carnivores, but not ALL scavengers are necessarily carnivores
        "Carnivore": ["Carnivore", "Insectivore", "Piscivore"],
        "Herbivore": ["Herbivore"]
    }

    if pd.isna(diet):
        return pd.NA

    for diet_type in diet_keywords:
        if (any([keyword in diet for keyword in diet_keywords[diet_type]])):
            return diet_type

    # All of the edge cases in our data happen to be omnivores
    # But if I had the time, I would also cross-reference diets with lists of "plant" or "animal" foods

    return "Omnivore"

df["Diet"] = df["Diet"].apply(clean_diet_column)

df.head(100)

cleaned_df = df.dropna(axis=0, how='any', subset=["Animal", "Diet", "Average Speed (km/h)"])
cleaned_df.to_csv("Freddy Yu - Cleaned Animal Data.csv")